import { Component, OnInit, NgZone } from '@angular/core';
import { DataService } from '../../services/data.service';
import { Router,ActivatedRoute } from '@angular/router';
@Component({
  selector: 'app-web-page',
  templateUrl: './web-page.page.html',
  styleUrls: ['./web-page.page.scss'],
})
export class WebPagePage implements OnInit {

  page_route:any;
  web_form:any;
  is_show:any = false;

  constructor(public db:DataService,public route : ActivatedRoute, public Ngzone : NgZone) { }

  ngOnInit() {
    this.route.queryParams.subscribe(async (params:any) => {
        // console.log(params);
       if (params && params.page_route) {
          this.page_route = params.page_route;
        //   this.is_show = true;
          this.get_form(this.page_route);
       }
    });
    // this.route.params.subscribe(res =>{
    //   console.log(res);
    //   if(res && res['page_route']){
    //     this.page_route = res['page_route'];
    //       // this.get_form(res['page_route']);  
    //   }
    // })
  }

  get_form(datas:any){
    this.db.web_form_dynamic(datas).subscribe(res=>{
      // console.log(res)
      if(res && res.data){
        this.web_form = res.data;
        this.is_show = true;
        this.Ngzone.run(()=>{
            this.web_form = this.web_form;
          })
        // console.log('success135');
        // setTimeout(() => { window.dispatchEvent(new Event('resize')); }, 100);
        // this.get_form_values();
      }
    })
  }

//   form_values:any={
//     // "data": {
//         "name": "customer-on-boarding",
//         "owner": "Administrator",
//         "creation": "2023-04-11 14:44:56.749851",
//         "modified": "2023-04-11 18:26:47.714078",
//         "modified_by": "Administrator",
//         "docstatus": 0,
//         "idx": 0,
//         "title": "Customer On Boarding",
//         "route": "customer-on-boarding",
//         "published": 1,
//         "doc_type": "Customers",
//         "module": "Ecommerce Business Store",
//         "is_standard": 0,
//         "login_required": 0,
//         "allow_multiple": 0,
//         "allow_edit": 0,
//         "allow_delete": 0,
//         "apply_document_permissions": 0,
//         "allow_print": 0,
//         "allow_comments": 0,
//         "show_attachments": 0,
//         "allow_incomplete": 0,
//         "max_attachment_size": 0,
//         "show_list": 0,
//         "show_sidebar": 0,
//         "button_label": "Save",
//         "doctype": "Web Form",
//         "list_columns": [],
//         "web_form_fields": [
//             {
//                 "name": "1e26757bf9",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 1,
//                 "fieldname": "",
//                 "fieldtype": "Page Break",
//                 "label": "Personal Details",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "8ff442316c",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 2,
//                 "fieldname": "",
//                 "fieldtype": "Section Break",
//                 "label": "",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "6a37b6f0ed",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 3,
//                 "fieldname": "first_name",
//                 "fieldtype": "Data",
//                 "label": "First name",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "14d35d37c6",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 4,
//                 "fieldname": "last_name",
//                 "fieldtype": "Data",
//                 "label": "Last Name",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "f6e2bbe13a",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 5,
//                 "fieldname": "phone",
//                 "fieldtype": "Data",
//                 "label": "Mobile Number",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "Phone",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//               "name": "f6e2bbe13a",
//               "owner": "Administrator",
//               "creation": "2023-04-11 14:44:56.749851",
//               "modified": "2023-04-11 18:26:47.714078",
//               "modified_by": "Administrator",
//               "docstatus": 0,
//               "idx": 5,
//               "fieldname": "alternate_phone",
//               "fieldtype": "Data",
//               "label": "Alternate Mobile Number",
//               "allow_read_on_all_link_options": 0,
//               "reqd": 0,
//               "read_only": 0,
//               "show_in_filter": 0,
//               "hidden": 0,
//               "options": "Phone",
//               "max_length": 0,
//               "max_value": 0,
//               "parent": "customer-on-boarding",
//               "parentfield": "web_form_fields",
//               "parenttype": "Web Form",
//               "doctype": "Web Form Field"
//           },
          
//           {
//             "name": "b202501b43",
//             "owner": "Administrator",
//             "creation": "2023-04-11 14:44:56.749851",
//             "modified": "2023-04-11 18:26:47.714078",
//             "modified_by": "Administrator",
//             "docstatus": 0,
//             "idx": 6,
//             "fieldname": "email",
//             "fieldtype": "Data",
//             "label": "Customer Email",
//             "allow_read_on_all_link_options": 0,
//             "reqd": 0,
//             "read_only": 0,
//             "show_in_filter": 0,
//             "hidden": 0,
//             "options": "Email",
//             "max_length": 0,
//             "max_value": 0,
//             "parent": "customer-on-boarding",
//             "parentfield": "web_form_fields",
//             "parenttype": "Web Form",
//             "doctype": "Web Form Field"
//         },
//           {
//             "name": "f6e2bbe13a",
//             "owner": "Administrator",
//             "creation": "2023-04-11 14:44:56.749851",
//             "modified": "2023-04-11 18:26:47.714078",
//             "modified_by": "Administrator",
//             "docstatus": 0,
//             "idx": 5,
//             "fieldname": "address",
//             "fieldtype": "Geo Location",
//             "label": "Personal Address as per AADHAR",
//             "allow_read_on_all_link_options": 0,
//             "reqd": 0,
//             "read_only": 0,
//             "show_in_filter": 0,
//             "hidden": 0,
//             "options": "Phone",
//             "max_length": 0,
//             "max_value": 0,
//             "parent": "customer-on-boarding",
//             "parentfield": "web_form_fields",
//             "parenttype": "Web Form",
//             "doctype": "Web Form Field"
//         },
//         {
//           "name": "2aaf3231f9",
//           "owner": "Administrator",
//           "creation": "2023-04-11 14:44:56.749851",
//           "modified": "2023-04-11 18:26:47.714078",
//           "modified_by": "Administrator",
//           "docstatus": 0,
//           "idx": 20,
//           "fieldname": "landmark",
//           "fieldtype": "Data",
//           "label": "Landmark",
//           "allow_read_on_all_link_options": 0,
//           "reqd": 0,
//           "read_only": 0,
//           "show_in_filter": 0,
//           "hidden": 0,
//           "max_length": 0,
//           "max_value": 0,
//           "parent": "customer-on-boarding",
//           "parentfield": "web_form_fields",
//           "parenttype": "Web Form",
//           "doctype": "Web Form Field"
//       },
//       {
//           "name": "eb88243370",
//           "owner": "Administrator",
//           "creation": "2023-04-11 14:44:56.749851",
//           "modified": "2023-04-11 18:26:47.714078",
//           "modified_by": "Administrator",
//           "docstatus": 0,
//           "idx": 21,
//           "fieldname": "country",
//           "fieldtype": "Data",
//           "label": "Country",
//           "allow_read_on_all_link_options": 0,
//           "reqd": 1,
//           "read_only": 0,
//           "show_in_filter": 0,
//           "hidden": 0,
//           "max_length": 0,
//           "max_value": 0,
//           "parent": "customer-on-boarding",
//           "parentfield": "web_form_fields",
//           "parenttype": "Web Form",
//           "doctype": "Web Form Field"
//       },
//       {
//           "name": "8d4ab9445f",
//           "owner": "Administrator",
//           "creation": "2023-04-11 14:44:56.749851",
//           "modified": "2023-04-11 18:26:47.714078",
//           "modified_by": "Administrator",
//           "docstatus": 0,
//           "idx": 22,
//           "fieldname": "state",
//           "fieldtype": "Data",
//           "label": "State",
//           "allow_read_on_all_link_options": 0,
//           "reqd": 1,
//           "read_only": 0,
//           "show_in_filter": 0,
//           "hidden": 0,
//           "max_length": 0,
//           "max_value": 0,
//           "parent": "customer-on-boarding",
//           "parentfield": "web_form_fields",
//           "parenttype": "Web Form",
//           "doctype": "Web Form Field"
//       },
//       {
//           "name": "7530879cd5",
//           "owner": "Administrator",
//           "creation": "2023-04-11 14:44:56.749851",
//           "modified": "2023-04-11 18:26:47.714078",
//           "modified_by": "Administrator",
//           "docstatus": 0,
//           "idx": 23,
//           "fieldname": "city_or_town",
//           "fieldtype": "Data",
//           "label": "City/Town",
//           "allow_read_on_all_link_options": 0,
//           "reqd": 1,
//           "read_only": 0,
//           "show_in_filter": 0,
//           "hidden": 0,
//           "max_length": 0,
//           "max_value": 0,
//           "parent": "customer-on-boarding",
//           "parentfield": "web_form_fields",
//           "parenttype": "Web Form",
//           "doctype": "Web Form Field"
//       },
//       {
//           "name": "7189bc3435",
//           "owner": "Administrator",
//           "creation": "2023-04-11 14:44:56.749851",
//           "modified": "2023-04-11 18:26:47.714078",
//           "modified_by": "Administrator",
//           "docstatus": 0,
//           "idx": 24,
//           "fieldname": "zip_code",
//           "fieldtype": "Data",
//           "label": "Zip Code",
//           "allow_read_on_all_link_options": 0,
//           "reqd": 1,
//           "read_only": 0,
//           "show_in_filter": 0,
//           "hidden": 0,
//           "max_length": 0,
//           "max_value": 0,
//           "parent": "customer-on-boarding",
//           "parentfield": "web_form_fields",
//           "parenttype": "Web Form",
//           "doctype": "Web Form Field"
//       },
//       {
//         "name": "c5e8cad8f0",
//         "owner": "Administrator",
//         "creation": "2023-04-11 14:44:56.749851",
//         "modified": "2023-04-11 18:26:47.714078",
//         "modified_by": "Administrator",
//         "docstatus": 0,
//         "idx": 36,
//         "fieldname": "",
//         "fieldtype": "Page Break",
//         "label": "Business Details",
//         "allow_read_on_all_link_options": 0,
//         "reqd": 0,
//         "read_only": 0,
//         "show_in_filter": 0,
//         "hidden": 0,
//         "options": "",
//         "max_length": 0,
//         "max_value": 0,
//         "parent": "customer-on-boarding",
//         "parentfield": "web_form_fields",
//         "parenttype": "Web Form",
//         "doctype": "Web Form Field"
//     },
//     {
//       "name": "8ff442316c",
//       "owner": "Administrator",
//       "creation": "2023-04-11 14:44:56.749851",
//       "modified": "2023-04-11 18:26:47.714078",
//       "modified_by": "Administrator",
//       "docstatus": 0,
//       "idx": 2,
//       "fieldname": "",
//       "fieldtype": "Section Break",
//       "label": "",
//       "allow_read_on_all_link_options": 0,
//       "reqd": 0,
//       "read_only": 0,
//       "show_in_filter": 0,
//       "hidden": 0,
//       "options": "",
//       "max_length": 0,
//       "max_value": 0,
//       "parent": "customer-on-boarding",
//       "parentfield": "web_form_fields",
//       "parenttype": "Web Form",
//       "doctype": "Web Form Field"
//   },
//             {
//                 "name": "103d4a29df",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 7,
//                 "fieldname": "gender",
//                 "fieldtype": "Link",
//                 "label": "Gender",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "Gender",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "f8458d0fc4",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 8,
//                 "fieldname": "dob",
//                 "fieldtype": "Data",
//                 "label": "Date Of Birth",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "86f48dd111",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 9,
//                 "fieldname": "customer_type",
//                 "fieldtype": "Select",
//                 "label": "Customer Type",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 1,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "\nCompany\nFreelancer",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "b7776332f2",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 10,
//                 "fieldname": "no_of_employees",
//                 "fieldtype": "Int",
//                 "label": "No. of Employees",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 1,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "depends_on": "eval: doc.customer_type == \"Company\"",
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "fec11f61a8",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 11,
//                 "fieldname": "table_6",
//                 "fieldtype": "Table",
//                 "label": "Customer Address",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "Customer Address",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "50499a452f",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 12,
//                 "fieldname": "viewed_products",
//                 "fieldtype": "Table",
//                 "label": "Viewed Products",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "Customer Viewed Product",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "d4eb129bca",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 13,
//                 "fieldname": "set_new_password",
//                 "fieldtype": "Data",
//                 "label": "Set New Password",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "43aece8869",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 14,
//                 "fieldname": "is_group",
//                 "fieldtype": "Check",
//                 "label": "Is Group",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "default": "0",
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "7339e17de2",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 15,
//                 "fieldname": "parent_level",
//                 "fieldtype": "Link",
//                 "label": "Parent",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "Customers",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "5b5f63fbf7",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 16,
//                 "fieldname": "business_name",
//                 "fieldtype": "Data",
//                 "label": "Business Name",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "28b323c6e5",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 17,
//                 "fieldname": "establishment_year",
//                 "fieldtype": "Data",
//                 "label": "Establishment Year",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "3afef60ddd",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 18,
//                 "fieldname": "business_type",
//                 "fieldtype": "Select",
//                 "label": "Business Type",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "\nFruits Retailer\nKirana Store\nGrocery Store\nWholeSaler\nModern Trade\nE-Commerce",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "9053729e26",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 19,
//                 "fieldname": "business_address_asper_kyc_document",
//                 "fieldtype": "Data",
//                 "label": "Business Address as Per KYC Document",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//                       {
//                 "name": "bf0fa042b7",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 25,
//                 "fieldname": "store_front_image",
//                 "fieldtype": "Attach Image",
//                 "label": "Store Front Image",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "ad87211361",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 26,
//                 "fieldname": "store_closeup_images",
//                 "fieldtype": "Attach Image",
//                 "label": "Store Closeup Images",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "634734d150",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 27,
//                 "fieldname": "store_operator_image",
//                 "fieldtype": "Attach Image",
//                 "label": "Store Operator Image",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "998a3de190",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 28,
//                 "fieldname": "gst_in",
//                 "fieldtype": "Data",
//                 "label": "GSTIN",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "4f1170b3f1",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 29,
//                 "fieldname": "weekly_off",
//                 "fieldtype": "Select",
//                 "label": "Weekly Off",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "\nSunday\nMonday\nTuesday\nWednesday\nThursday\nFriday\nSaturday",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "03bf1e2573",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 30,
//                 "fieldname": "operate_multiple_stores",
//                 "fieldtype": "Check",
//                 "label": "I Operate Multiple Stores",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 0,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "default": "0",
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "3427fc3f96",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 31,
//                 "fieldname": "identity_proof",
//                 "fieldtype": "Select",
//                 "label": "Identity Proof",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "\nAADHAR\nDriving License\nVoter ID\nPAN Card",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "fc3cd013d6",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 32,
//                 "fieldname": "identity_proof_attachment",
//                 "fieldtype": "Attach",
//                 "label": "Identity Proof Attachment",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "14c2eb1952",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 33,
//                 "fieldname": "address_proof",
//                 "fieldtype": "Select",
//                 "label": "Address Proof",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "\nAADHAR\nDriving License\nVote ID\nPAN Card",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "ee0c46e74d",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 34,
//                 "fieldname": "address_proof_attachment",
//                 "fieldtype": "Attach",
//                 "label": "Address Proof Attachment",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             {
//                 "name": "5025854f4a",
//                 "owner": "Administrator",
//                 "creation": "2023-04-11 14:44:56.749851",
//                 "modified": "2023-04-11 18:26:47.714078",
//                 "modified_by": "Administrator",
//                 "docstatus": 0,
//                 "idx": 35,
//                 "fieldname": "customer_business_document",
//                 "fieldtype": "Table",
//                 "label": "Customer Business Document",
//                 "allow_read_on_all_link_options": 0,
//                 "reqd": 1,
//                 "read_only": 0,
//                 "show_in_filter": 0,
//                 "hidden": 0,
//                 "options": "Customer Business Attachment",
//                 "max_length": 0,
//                 "max_value": 0,
//                 "parent": "customer-on-boarding",
//                 "parentfield": "web_form_fields",
//                 "parenttype": "Web Form",
//                 "doctype": "Web Form Field"
//             },
//             // {
//             //     "name": "c5e8cad8f0",
//             //     "owner": "Administrator",
//             //     "creation": "2023-04-11 14:44:56.749851",
//             //     "modified": "2023-04-11 18:26:47.714078",
//             //     "modified_by": "Administrator",
//             //     "docstatus": 0,
//             //     "idx": 36,
//             //     "fieldname": "",
//             //     "fieldtype": "Page Break",
//             //     "label": "KYC Documents",
//             //     "allow_read_on_all_link_options": 0,
//             //     "reqd": 0,
//             //     "read_only": 0,
//             //     "show_in_filter": 0,
//             //     "hidden": 0,
//             //     "options": "",
//             //     "max_length": 0,
//             //     "max_value": 0,
//             //     "parent": "customer-on-boarding",
//             //     "parentfield": "web_form_fields",
//             //     "parenttype": "Web Form",
//             //     "doctype": "Web Form Field"
//             // }
//         ]
//     // }
// }

}
